name: Build and push image

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}

      - uses: cachix/install-nix-action@v30

      - name: Build container image
        id: build
        run: |
          echo "result=$(nix build --no-link --print-out-paths .#docker)" >> "$GITHUB_OUTPUT"

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish container images
        env:
          IMAGES: ${{ steps.meta.outputs.tags }}
          RESULT: ${{ steps.build.outputs.result }}
        run: |
          for img in $IMAGES; do
            skopeo copy "docker-archive:$RESULT" "docker://$img"
          done
      - name: Publish Helm chart
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          helm package --version "$VERSION" --app-version "$GITHUB_REF_NAME" -d pkg/ chart/
          helm push ./pkg/*.tgz "oci://ghcr.io/$GITHUB_REPOSITORY_OWNER"
